//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogEngine.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlogEngine.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The syndication feed must be of type BlogEngine.Core.Entities.Syndication.Atom.AtomFeed in order to be filled or written by this data adapter..
        /// </summary>
        internal static string ExceptionAtomSyndicationFeedAdapterInvalidFeedType {
            get {
                return ResourceManager.GetString("ExceptionAtomSyndicationFeedAdapterInvalidFeedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The AtomText.Type property is invalid..
        /// </summary>
        internal static string ExceptionAtomTextTypeInvalid {
            get {
                return ResourceManager.GetString("ExceptionAtomTextTypeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string value cannot be null or empty..
        /// </summary>
        internal static string ExceptionEmptyStringMessage {
            get {
                return ResourceManager.GetString("ExceptionEmptyStringMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string being parsed is not in the expected format..
        /// </summary>
        internal static string ExceptionParseFormatException {
            get {
                return ResourceManager.GetString("ExceptionParseFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RssCloud.Protocol property is invalid..
        /// </summary>
        internal static string ExceptionRssCloudProtocolInvalid {
            get {
                return ResourceManager.GetString("ExceptionRssCloudProtocolInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An RssItem must have either its Title or Description property set to a non-empty value..
        /// </summary>
        internal static string ExceptionRssItemDoesNotHaveADescriptor {
            get {
                return ResourceManager.GetString("ExceptionRssItemDoesNotHaveADescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The syndication feed must be of type BlogEngine.Core.Entities.Syndication.Rss.RssFeed in order to be filled or written by this data adapter..
        /// </summary>
        internal static string ExceptionRssSyndicationFeedAdapterInvalidFeedType {
            get {
                return ResourceManager.GetString("ExceptionRssSyndicationFeedAdapterInvalidFeedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XmlWriterType enumeration is WriterType.None, which is not valid..
        /// </summary>
        internal static string ExceptionSyndicationFeedAdapterInvalidWriterType {
            get {
                return ResourceManager.GetString("ExceptionSyndicationFeedAdapterInvalidWriterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SyndicationFeed.Header property is a null reference (Nothing in Visual Basic)..
        /// </summary>
        internal static string ExceptionSyndicationFeedHeaderEmpty {
            get {
                return ResourceManager.GetString("ExceptionSyndicationFeedHeaderEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SyndicationFeed.Header.Source property is a null or empty string..
        /// </summary>
        internal static string ExceptionSyndicationFeedHeaderSourceEmpty {
            get {
                return ResourceManager.GetString("ExceptionSyndicationFeedHeaderSourceEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource located at the URI specified in SyndicationFeed.Header.Source property contains no data..
        /// </summary>
        internal static string ExceptionSyndicationFeedHeaderSourceHasNoData {
            get {
                return ResourceManager.GetString("ExceptionSyndicationFeedHeaderSourceHasNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Reader property must be set prior to calling the Fill method..
        /// </summary>
        internal static string ExceptionXmlSyndicationFeedAdapterReaderEmpty {
            get {
                return ResourceManager.GetString("ExceptionXmlSyndicationFeedAdapterReaderEmpty", resourceCulture);
            }
        }
    }
}
