<%@ Page Language="C#" MasterPageFile="~/admin/admin.master" AutoEventWireup="true" CodeFile="Categories.aspx.cs" Inherits="admin_Pages_Categories" Title="Categories" %>
<asp:Content ID="Content1" ContentPlaceHolderID="cphAdmin" Runat="Server">

  <label for="txtNewCategory">Add new category</label><br />
  <asp:TextBox runat="Server" ID="txtNewCategory" Width="200" />  
  <asp:Button runat="server" ID="btnAdd" Text="Add category" ValidationGroup="new" />
  <asp:RequiredFieldValidator runat="Server" ValidationGroup="new" ControlToValidate="txtNewCategory" ErrorMessage="Please enter a valid name" /><br /><hr />

  <asp:GridView runat="server" ID="grid" CssClass="category"  
    UseAccessibleHeader="true" 
    GridLines="None"
    AutoGenerateColumns="false" 
    AlternatingRowStyle-CssClass="alt" 
    AutoGenerateDeleteButton="true" 
    AutoGenerateEditButton="true">
    <Columns>      
      <asp:TemplateField HeaderText="Name">
        <ItemTemplate>
          <%# Eval("value") %>
        </ItemTemplate>
        <EditItemTemplate>
          <asp:TextBox runat="server" ID="txtName" Text='<%# Eval("value") %>' />
        </EditItemTemplate>
      </asp:TemplateField>
    </Columns>
  </asp:GridView>
  
</asp:Content>