<?xml version="1.0" encoding="utf-8"?><Database Name="BlogEngineFileStore" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=localhost;Initial Catalog=BlogEngineFileStore;Integrated Security=True" SettingsObjectName="ClassLibrary1.Properties.Settings" SettingsPropertyName="BlogEngineFileStoreConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.be_FileStoreDirectory" Member="be_FileStoreDirectories">
    <Type Name="be_FileStoreDirectory">
      <Column Name="Id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="BlogID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FullPath" Type="System.String" DbType="VarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAccess" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModify" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="be_FileStoreDirectory_be_FileStoreFile" Member="be_FileStoreFiles" ThisKey="Id" OtherKey="ParentDirectoryID" Type="be_FileStoreFile" />
    </Type>
  </Table>
  <Table Name="dbo.be_FileStoreFileThumbs" Member="be_FileStoreFileThumbs">
    <Type Name="be_FileStoreFileThumb">
      <Column Name="thumbnailId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FileId" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="size" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="contents" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="be_FileStoreFile_be_FileStoreFileThumb" Member="be_FileStoreFile" ThisKey="FileId" OtherKey="FileID" Type="be_FileStoreFile" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.be_FileStoreFiles" Member="be_FileStoreFiles">
    <Type Name="be_FileStoreFile">
      <Column Name="FileID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ParentDirectoryID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="FullPath" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Contents" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Size" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastAccess" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastModify" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="be_FileStoreFile_be_FileStoreFileThumb" Member="be_FileStoreFileThumbs" ThisKey="FileID" OtherKey="FileId" Type="be_FileStoreFileThumb" />
      <Association Name="be_FileStoreDirectory_be_FileStoreFile" Member="be_FileStoreDirectory" ThisKey="ParentDirectoryID" OtherKey="Id" Type="be_FileStoreDirectory" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>